//Book data mutations
export const LOAD_BOOK_DATA = 'LOAD_BOOK_DATA'
export const VALIDATE_BOOK = 'VALIDATE_BOOK'
export const SELECT_PAGE = 'SELECT_PAGE'
export const EDIT_PAGE = 'EDIT_PAGE'
export const RENDER_PAGE = 'RENDER_PAGE'
export const DELETE_PAGE = 'DELETE_PAGE'
export const ADD_PAGE = 'ADD_PAGE'
export const CHANGE_STARTING_PAGE = 'CHANGE_STARTING_PAGE'
export const MODULE_REF_DELETED = 'MODULE_REF_DELETED'
export const MODULE_REF_ADDED = 'MODULE_REF_ADDED'
export const CHANGE_LINK_PAGEID = 'CHANGE_LINK_PAGEID'

//Editor status mutations -- keeps info about editor (what is open, edited, history, etc)
export const CHANGE_MINI_PAGE_LIST_STATUS = 'CHANGE_MINI_PAGE_LIST_STATUS'
export const CHANGE_ELEMENTS_LIST_STATUS = 'CHANGE_ELEMENTS_LIST_STATUS'
export const CHANGE_MINI_PAGE_SHOWN_METHOD = 'CHANGE_MINI_PAGE_SHOWN_METHOD'
export const ONLY_ERROR_MINI_PAGE_SHOWN_METHOD = 'ONLY_ERROR_MINI_PAGE_SHOWN_METHOD'
export const ADD_UNDO_ACTION = 'ADD_UNDO_ACTION'
export const REMOVE_UNDO_ACTION = 'REMOVE_UNDO_ACTION'
export const ADD_REDO_ACTION = 'ADD_REDO_ACTION'
export const REMOVE_REDO_ACTION = 'REMOVE_REDO_ACTION'

//Modules mutations
export const ADD_WORKSPACES = 'ADD_WORKSPACES'
export const MODULES_PROCESS_LOCAL_DATA = 'MODULES_PROCESS_LOCAL_DATA'
export const MODULES_BUILD_REVERSE_INFO = 'MODULES_BUILD_REVERSE_INFO'
export const MODULES_UPDATE_REV = 'MODULES_UPDATE_REV'
export const MODULES_PAGE_DELETED = 'MODULES_PAGE_DELETED'
export const MODULES_PAGE_ADDED = 'MODULES_PAGE_ADDED'

//Item module mutations
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM'
export const SELECTED_ITEM_CHANGED = 'SELECTED_ITEM_CHANGED'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const SET_REVERSE_INFO_ITEM = 'SET_REVERSE_INFO_ITEM'